header:
  license:
    spdx-id: MIT
    copyright-owner: Guy Erreich
    content: |
      Copyright (c) 2026 Guy Erreich

      SPDX-License-Identifier: MIT
  paths:
    - plugins/ankyr-review/hooks
    - scripts
  paths-ignore:
    - '**/*.json'
    - plugins/ankyr-review/hooks/tests
    - plugins/ankyr-review/hooks/state
